### PR TITLE
Remove test stuff from devpi-client's packaging

### PR DESCRIPTION
**Pull request by wimglenn**
Closes https://github.com/devpi/devpi/issues/746 

- Make the tox dependency optional.  Can use `pip install devpi-client[test]` to pull it in.
- Don't export a `testing` package to site-packages on `pip install devpi-client` 

```
$ ls ~/.venv/lib/python3.8/site-packages/testing
conftest.py    __init__.py  reqmock.py  test_functional.py  test_install.py      test_login.py  test_push.py    test_test.py    test_use.py
functional.py  __pycache__  simpypi.py  test_index.py       test_list_remove.py  test_main.py   test_pypirc.py  test_upload.py  test_user.py
```

### CODE REVIEW

**Comment by wimglenn** [comment]
@fschulze   Could you take a look at the appveyor build please?  I don't really understand the problem, that fails somewhere in `devpi-server.exe --version` but for some reason it's using a Python-3.4 runtime in the py27 test, which seems pretty weird. Configuration problem?

**Comment by fschulze** [comment]
As it is now the "devpi test" command fails with an unhelpful import error on a clean installation without ``[test]``. We are currently in contact with companies that pay for this feature to discuss possible solutions. Until that is cleared up I won't accept this PR.

I will investigate whether removing the ``testing`` package causes no other issues, but I think that part is fine.

You can ignore the AppVeyor failure, it is unrelated and I will look into it. The reason Python 3.x is used in the Python 2.7 tests is that the functional tests run devpi-server in a virtualenv and because it will soon drop Python 2.7 support it uses Python 3.x to run it.

**Comment by wimglenn** [comment]
@fschulze  How about to add a message in `devpi test` which tells user they need to install extra `devpi-client[test]` to use that feature?  Like a message on stderr and then exit 1.

**Comment by fschulze** [comment]
@wimglenn that is the consensus we got from asking about it. When ``devpi test`` is run, it should try to find a ``tox`` executable in the path and if that fails try to import it. If nothing can be found something along this should be displayed: ``No tox executable or module could be found. Use "pip install tox" or some other way to ensure tox is available as an executable or importable by devpi-client``.

This would also be a breaking change requiring a major version bump and proper ``news`` entry.

**Comment by fschulze** [comment]
Checking for the ``tox`` executable would be a new feature, so that would be a nice to have, but the other requirements stand for accepting this PR.

**Comment by wimglenn** [comment]
Replaced with https://github.com/devpi/devpi/pull/890

**Pull request closed without merging**
