### PR TITLE
Versioned static resources

### PR DESCRIPTION
**Pull request by fschulze**

### CODE REVIEW

**Comment by gotcha** [comment]
LGTM when tests pass

**Comment by RonnyPfannschmidt** [comment]
how does this behave with a webserver in front? (thats possibly serving the static files)

**Comment by fschulze** [comment]
@RonnyPfannschmidt With the example nginx config only the releases and docs are served by nginx and they have a different route. I only change the URL for the static files route in the devpi-web package and for the theme path option.

**Comment by RonnyPfannschmidt** [comment]
i see, thanks for clarifying 👍

**Pull request merged**
