### PR TITLE
Accept PyPy 5.10 version string

### LINKED ISSUE #496: Cannot upload binary wheels created using PyPy 5.10
This is #355 again.  The version string is now 4 numbers long (2510): `cryptography-2.1.4-pp2510-pypy_41-linux_x86_64.whl`.

### PR DESCRIPTION
**Pull request by WolverineFan**
Fixes #496 (though it's kind of getting silly now).

### CODE REVIEW

**Comment by WolverineFan** [comment]
Looks like the travis problem is a network issue...

**Comment by fschulze** [comment]
I'd say we should just remove that assert.

**Comment by WolverineFan** [comment]
@fschulze I could also just change it to:
```python
        assert len(pyversion) > 0
```

**Comment by WolverineFan** [comment]
Argh.  GitHub apparently didn't show me all the recent activity until I added my comment.  Looks good to me, I'll close this.

**Pull request closed without merging**
