### PR TITLE
Properly set up HTTP basic auth during `devpi test`

### PR DESCRIPTION
**Pull request by vytas7**
* Use basic auth when downloading packages
 * Pass basic auth-enabled Pip index to tox

### CODE REVIEW

**Comment by vytas7** [comment]
The proposed patchset seems to solve the problem at hand, but I need advice on writing good unit tests for these, and Devpi tests are actually somewhat harder to understand than the code base itself :smiling_imp: 

Could something in spirit of ``client/testing/test_upload.py``: ``test_post_includes_auth_info`` do, just attaching fake basic auth and verifying the *requests* method has been called with *auth* / *cert* parameters?

**Comment by fschulze** [comment]
@vytas7 Thanks! Yes, the ``test_post_includes_auth_info`` approach is totally fine.

I'm not sure if and where we should warn that the basic auth info will be in the uploaded test result data. If someone uses basic auth, then the test results are also behind that, so it shouldn't be an issue.

An alternative would be to create a ``pip.cfg`` in the temporary virtualenv which includes the basic auth info. I haven't tested that, but it might hide the basic auth info in that case.

**Comment by vytas7** [comment]
Thanks for your input @fschulze !

I don't think it is a could idea to add unnecessary complexity by hacking in some temporary ``pip.cfg`` -- that would make it harder to manually rerun the commands from the report should the need arise.

In most common scenarios, it shouldn't be a problem users accessing reports with credentials since, as you point out, they would need either the same credentials, or another trusted way to authorize (such as internal network access like we do at work).
I added a warning for those rare scenarios where it is not the case, in a similar vein to what you get when configuring a client for a basic-auth protected Devpi.

If I were to gripe a bit about Devpi code base, I think testing could be made easier using [mock](https://docs.python.org/3/library/unittest.mock.html) (available on PyPi, native in Python 3.3+), [requests_mock](https://pypi.python.org/pypi/requests-mock) etc, but I did not want to make any substantial changes to the code base I am not very familiar with.

On the positive side, I have finally got the time to take a look at this again, and to finish the unit tests.

**Comment by fschulze** [comment]
@vytas7 we use mock in some places already. Personally I try to avoid using it too much though, because I was bitten by it hiding changes in the mocked parts.
Some of the tools like requests_mock didn't exist or where not known when devpi tests were written.
The tests could be better in places, but as with most things they got complex with the growing/changing code base and there was no time/pressing need to refactor them yet.

**Comment by vytas7** [comment]
> but as with most things they got complex with the growing/changing code base and there was no time/pressing need to refactor them yet.

Fully understood @fschulze , it is true for every large project with a living code base.

**Comment by fschulze** [comment]
@vytas7 can you please add a changelog entry as described in https://github.com/devpi/devpi/blob/master/CONTRIBUTING.rst?

**Comment by vytas7** [comment]
Sure, will fix!

I saw in the ``CHANGELOG`` that external contributors get thanked, shall I... umm thank myself? :smile:

**Comment by fschulze** [comment]
@vytas7 you may do so :) We are still thinking about changing that, maybe adopt the way tox does it now.

**Comment by vytas7** [comment]
@fschulze do not hesitate to let me know in case anything else if needed for this PR.

**Pull request merged**
