### PR TITLE
Fix #565: Don't list toxresults by default

### LINKED ISSUE #565: 'devpi list <package_name>' shows too detailed data
devpi-client version: 4.0.3

When invoking `devpi list <package_name>` devpi client actually lists few latest release files together with the test results. Fetching all tox results requires quite some time (especially when results are big). 

Would it make sense to display by default only the release files? User might want to view release files and tox results by adding -v flag: `devpi list <package_name> -v`.

### PR DESCRIPTION
**Pull request by fschulze**
@r2dan does this look good?

### CODE REVIEW

**Comment by fschulze** [comment]
Not sure this deserves a major version bump. Strictly speaking it's a backward incompatible change, but the output isn't easily machine readable, so I doubt it's used in scripts for example.

**Comment by r2dan** [comment]
Looks good. Regarding version bump - it's not an urgent thing so you can wait and release it with some other backward incompatible changes in the future.

**Comment by gotcha** [comment]
Are there already other easily machine readable ways to access the same info ?
If yes, the risk of no version bump is minor. If not, I would wait for version bump.

**Comment by fschulze** [comment]
The json info from the server is the best source for machine readable data.

**Pull request merged**
