### PR TITLE
Make search results compatible with pip showing INSTALLED/LATEST info

### PR DESCRIPTION
**Pull request by gdubicki**
Fixes https://github.com/devpi/devpi/issues/455

### CODE REVIEW

**Comment by fschulze** [comment]
Thanks for the PR. The ``test_pip_search`` test in devpi_web needs to be updated as well. It's easiest to just run ``tox -e py27`` in the ``web`` subdirectory to run the tests.

**Comment by gdubicki** [comment]
Sure, I will fix that. Thanks!

**Comment by gdubicki** [comment]
`test_pip_search` is fixed. Some other tests are failing, but I guess that will be fixed by https://github.com/devpi/devpi/pull/453.

**Comment by fschulze** [comment]
Yep, looks good

**Comment by gdubicki** [comment]
Thanks! Do you need anything else to merge it, @fschulze ?

**Pull request merged**
